services:
  django:
    build: order_service
    command: >
      /bin/sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./order_service/:/usr/src/order_service/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

  rabbitmq:
    restart: always
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 10s
      retries: 5

  celery:
    build: order_service
    command: celery -A orders worker -l info
    volumes:
      - ./order_service/:/code
    depends_on:
      rabbitmq:
        condition: service_healthy

  celery-beat:
    build: order_service
    command: celery -A orders beat -l info
    volumes:
      - ./order_service/:/code
    depends_on:
      rabbitmq:
        condition: service_healthy