# Generated by Django 4.2.7 on 2024-11-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=255)),
                ('courier', models.CharField(max_length=255)),
                ('foods', models.JSONField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
